### ISSUE TITLE
List command: query entries containing unicode

### ISSUE THREAD

**Issue by wflynny** [pubs/pubs#103]
Related to #15, #87 and maybe #28, #10.

I'm currently aliasing `pubs list "author:<author-name>"` as a primitive search command.  This works well for most cases but fails if the author's name contains unicode characters.  It would be nice to have some fuzzy matching or something similar.  For example,

    pubs list author:Grun
    pubs list author:Gr{\"u}n

fails to return any documents by author "Grün".  A work around is to just do the search using truncated query `pubs list author:Gr`, though that could lead to problems with larger repositories.

**Comment by omangin** [comment]
Thanks! There are actually several issues here.

1. The comparison during the search should occur on normalized unicode strings (except maybe when some option is set that we could call `--strict` or `--no-normalize`).

2. In your example, the author name should be converted to unicode before any manipulation is performed, by calling bibtexparser's `convert_to_unicode` customization. However I'm not in favor of changing the default to always apply the customization because this store the entries as unicode which would come into the way of user's preferences on how to store bibdata. If I'm correct not all version of latex accept unicode and that would also remove the protection of capitals within `{}`. The customization should only be applied for comparison and print. (Currently list also displays `\"u` if that's what in the bibdata.)

3. The search query should probably be compared to an ascii equivalent of the field's value. Following the same scheme as for case sensitivity: a search query with only unicode characters is compared to the ascii equivalent of the field (through [unidecode](https://pypi.python.org/pypi/Unidecode)) and a search query with non-unicode characters is compared to the unicode. The corresponding options to force the behavior would be `--transliterate` and `--no-transliterate`.

Obviously implementing #15 would solve 1 and 2.
