### ISSUE TITLE
pubs is not readily available in Window  CMD after pip installation

### ISSUE THREAD

**Issue by sjystu** [pubs/pubs#110]
Hello,

I was wondering if there would be any way you could upgrade pubs installation process  for Windows command line users.

In Linux, you can use "pubs" in command line as soon as you install it.
However, in Windows it does not seem to be added to PATH.

When I installed another Python package called "gscholar" using pip, it was automatically added to Windows PATH so that users can employ the alias in the CMD.

Please consider it.

Appreciatively,

**Comment by wflynny** [comment]
I think this just requires a change from `scripts=` to `entry_points=` in `setup.py` [[1]].  Looks like it may be recommended practice too [[2]].  

This should be too hard in theory, but has `pubs` been tested at all on Windows?  @omangin a Windows CI build would need to be made, correct?  How much work it that?

[1]: http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation
[2]: https://stackoverflow.com/a/28119736/1634191

**Comment by omangin** [comment]
Hi @sjystu. We indeed do not support Windows and I have honestly no idea about how `pip` installs things on it. However the `pubs` script that is currently used has little chance to execute since it explicitly refers to `/usr/bin/env python` as an interpreter.

I have created a branch with @wflynny's suggestion on using `entry_points` instead. You may try it to check whether that works. Note that it's likely that the rest of the code is not fully functional. We would be happy to get feedback on whether this works on Windows. (Windows support is however unfortunately far from our priority.)

Regarding switching to `entry_points`, it might be better practice since we delay more tasks to pip. The issue right now is that I am not fully sure it does not break autocompletion, which I need to double check. I'll open a PR regarding that.

**Comment by omangin** [comment]
Closing for now. Please re-open if you tried the latest version of the code with the _entry-point_ method and have more feedback.

**Comment by benureau** [comment]
@sjystu: could you tell us your version of Windows, python, and how it was installed?
@omangin: since Python 3.3, `#!/usr/bin/env python` is supported on Windows. See https://docs.python.org/3.6/using/windows.html#shebang-lines . If we support pubs on Windows one day, we might do it for >=3.3 only.

**Comment by sjystu** [comment]
Thank you so much for your kind response.

 

I used Python 3.5 on Windows 10 64 bit system.

FYI, I used Anaconda.

Please let me know if you need any other information from me.

 

Thanks.

**Comment by omangin** [comment]
@benureau Good to know. Do you mean that as an argument towards moving back to using a script? The `entry_point` solution seemed more elegant overall since we don't have to mention the interpreter at all and since it was anyway overruled by the entry point that the setup-tools were generating.

@sjystu Did you try the latest version of the code?
