### ISSUE TITLE
Issue with journal customization on empty field: remove journal customization?

### ISSUE THREAD

**Issue by omangin** [pubs/pubs#126]
Adding an article with an empty `journal = ""` field crashes pubs. This is because the journal customization does not create the dictionary with the `name` field when the original field is an empty string (the value in the bibdata remains `""`), which is not handled by [endecoder.py#L107](https://github.com/pubs/pubs/blob/master/pubs/endecoder.py#L107).

Although this is a quick thing to fix it raises the question of whether to keep the journal customization that is, for now, useless (it only moves the value to a name field in a dictionary and adds an `ID` field equal to the journal name minus the `' '`, `','`, and `'.'`).

On the one hand it would be good to have a structured representation of the journal when that is supported by bibtexparser in the future, but on the other hand it is currently adding complexity to the code without any  benefit.

Any thought?

**Comment by benureau** [comment]
I don't have much visibility of what it means in practice, but if the journal customization is not useful, then it should be done away with. Why does bibtexparser strips the name field if it is empty (https://github.com/sciunto-org/python-bibtexparser/blob/86f5833100aa6ada36a1917f9223eb7fdad6bbe3/bibtexparser/customization.py#L420)? 

When in doubt, we should lean towards preserving the original data inputed by the user (not removing fields because they are empty, for instance. We could also consider that if the `month` is not entered in english, it should not be an error, but be copied by pubs.).

**Comment by omangin** [comment]
> When in doubt, we should lean towards preserving the original data inputed by the user (not removing fields because they are empty, for instance.

Exactly! I will remove it.

> We could also consider that if the month is not entered in english, it should not be an error, but be copied by pubs.).

What do you mean exactly? Currently a `month = {janvier}` should work.

The only special treatment is for `month = jan` which is not correct bibtex but assumes that a bibtex `string` is defined to convert `jan` to something else. To address that `bibtexparser` automatically include some common strings (when the eponymous option is set). This however implies that the string is replaced when we write the bibtex. Finally `bibtexparser` uses `January` as a replacement for `jan` while `1` might be a better option (I would have to do more research on what these imply on the formatting); if so that would be a change to contribute upstream to `bibtexparser`.
