### ISSUE TITLE
'pubs note' fails with 'No such file or directory' without explanation

### ISSUE THREAD

**Issue by yurivict** [pubs/pubs#140]
System call log says that it looked for ```nano```.

Suggested fix: It should say that it can't find the editor ```nano```, and suggest how to select a different editor.

**Comment by yurivict** [comment]
FreeBSD 11.1, pubs-0.7.0

Command:
```
$ pubs note Harvey_2018
error: [Errno 2] No such file or directory
```

**Comment by benureau** [comment]
Thanks, I can reproduce the behavior. As a fix for your problem, you can either set the variable $EDITOR, or modify your pubsrc configuration file to modify the edit_cmd field.

**Comment by yurivict** [comment]
> As a fix for your problem, you can either set the variable $EDITOR, or modify your pubsrc configuration file to modify the edit_cmd field.

Yes, I know, thanks. Please make it suggest these solutions in the error message.

**Comment by omangin** [comment]
Indeed.  This has been discussed already in #46. The default was set to `vi` before being changed back to `nano` (a2911149003213290d11aee3b7d62fa94f0c3678). The current issue kind of demonstrates that `vi` is the only sane default since it is the only one (with `ex`) guaranteed to be there for all POSIX systems. As mentionned in #46, _inexperienced users_ are not really a concern.

> [vi] will always work, assuming that distributions that target inexperienced users (like Ubuntu) would have taken care of setting an appropriate $EDITOR which would be found by pubs. Although some users using the wrong distribution for them could get trapped by vi.

I will revert the default to it. We might consider putting a note in the documentation if this is deemed necessary.
