### ISSUE TITLE
Fix Pyfakefs for Python 2.7

### ISSUE THREAD

**Issue by benureau** [pubs/pubs#181]
See Travis results on #174

**Comment by omangin** [comment]
Not completely related but (since python 2.7, specially with pyfakefs is starting to be a pain) it could be good once this is solved to set a time for when we stop supporting python 2. We could deprecate it and continue supporting it for, say, one year (nothing prevent us then from supporting it a little longer). That way everyone would have been warned and we can drop it when it starts inducing too much additional work.

**Comment by benureau** [comment]
The problem seems to have been fixed on pyfakefs side. About Python 2, yes. The sunset date for Python 2 is 1st of January, 2020, so we can keep supporting Python 2 unofficially (as in, it works, but no promises) as long as nothing terribly inconvenient happens.
