### ISSUE TITLE
Win10 python 3.8 "pubs conf" "error: module 'os' has no attribute 'errno'"

### ISSUE THREAD

**Issue by eschen42** [pubs/pubs#220]
- I installed python 3.8 on Windows 10.
- I did `pip3 install pubs`
- I ensured that `pubs.exe` is on my PATH.
- I ran `pubs init`
- I tried to run `pubs conf`
- I got the following error message:
  - `error: module 'os' has no attribute 'errno'`

Any suggestions for how I ought to proceed?

I expect success if I fall back to Windows Subsystem for Linux (aka WSL).

Thank you for `pubs` - it totally rocks!

**Comment by benureau** [comment]
Hi @eschen42,
Indeed, pubs is not tested under Windows. However, it seems so far unrelated to this, there was a typo, and I fixed it. I think the next problem you will encounter is that the editor is not properly configured for Windows, which is needed for running `pubs conf`... yeah, not smart. You can edit the configuration manually, the default path is `~/.pubsrc`. If you find a good default that works on a vanilla windows installation, could you tell us so that we set it up as default for the configuration on windows?

**Comment by rien333** [comment]
@benureau  Actually, I don't think the problem is with their setup. python3.7 removed errno from the os module, hence the error. See the bottom item of the python 3.7 changelog: https://docs.python.org/3.7/whatsnew/3.7.html#changes-in-the-python-api

You should probably reopen the issue, though as the resource above lists, the fix should be fairly trivial. (i.e. use `import errno` directly)

**Comment by benureau** [comment]
@rien333: yes indeed. The changes in the code have already been made, back in April:
https://github.com/pubs/pubs/commit/246a00671e78b9d4353cea9b2eb0c0d07e3682c5

If you feel there is another problem, please reopen the issue.
