### ISSUE TITLE
[bug] tags on non-existing entries isn't reportet

### ISSUE THREAD

**Issue by 73** [pubs/pubs#35]
Reproduction:

```
pubs tag nonexsistingkey sometag
```
What happens:
```

```
Expectation:
```
Sorry, I don't know document 'nonexsistingkey'.
```

**Comment by humm** [comment]
Yep, the `tag` command is horribly overloaded right now. This is not technically a bug, just faulty design. I am looking into making it more predictable.

**Comment by omangin** [comment]
Indeed. This is because the code was made to hande things such as
``pubs tag onetag othertags``
as well as
``pubs tag citekey tags``

Since there is no way to do that in predictably, I will remove the first option.

I would also generally be in favor of dropping the syntax `pubs tag tags` in favor of `pubs list`. If we keep it anyway, we should appropriately delegate that to a function shared with the list command or even use the list command directly.
