### ISSUE TITLE
add version control to pubs library

### ISSUE THREAD

**Issue by beuerle** [pubs/pubs#68]
So far it is possible to keep one's pubs library in version control by initiating a git repository and keeping track of changes of the individual files in `bib`, `meta` and `notes` manually by hand (ignore files in `doc` if preferred).

Feature request: add version control possibility

* configure VCS in `.pubsrc` (git, hg, bazaar, ...)
* configure behaviour in `.pubsrc`
	* include `doc`
	* ...
* move `.pubsrc` to config folder (`.pubs/`) to keep track of config changes?
* git: use [`GitPython`](http://gitpython.readthedocs.io/) (or another library?) to implement version control
* make an auto-commit whenever a new reference is added, or an existing reference is modified or deleted

**Comment by omangin** [comment]
Thanks @beuerle. That's indeed a behavior that we have thought about including as a plugin but chose not to implement until now. It is actually a good example of what plugins are for since this does not belong to the core functionalities of pubs.

The road to implement the plugin however requires logging the various events (basically all modifications to data or documents) at the level of the repository, potentially through a _hook_ system defined on these events. This would also benefit a _log_ plugin to write these events to a file but requires a bit of work. This is not our priority right now but if you want to contribute the functionality, we'll be happy to merge it. If others are interested in this, please also let us know.

In the meanwhile, you can either commit manually or use a program such as https://github.com/nesquena/gitdocs to monitor the files and commit on changes.

**Comment by beuerle** [comment]
FWIW, I just configured an alias in `pubsrc` for that for now:

```
cm = !git add . && git commit -a -m autocommit && git push
```

**Comment by zamlz** [comment]
Just want to say that I'm really diggin this project. Of all the cli bib apps i've tried, I think this one seems to fit with what I want it to do. I've only added a couple papers as of now, but if I really like this, I'll move my thing from zotero to pubs. I also would really like git functionality and wouldn't mind looking in how to do this in the future. Hopefully this winter break.

**Comment by zamlz** [comment]
Have you guys seen the program [password-store](https://www.passwordstore.org/)? I was thinking of maybe implementing it similar to this. All commands should automatically make commits to the repo, but if the user wants to do other stuff to their pubs folder, then can just do,
```
pubs git $GIT_CMD
```

**Comment by omangin** [comment]
Yes, something like that would be great!

We had in mind to implement it as a plugin shipped by default and hence that can be activated by a simple config option. The [events](https://github.com/pubs/pubs/blob/master/pubs/events.py) have been included to support this kind of functionalities. It should be enough that the plugin registers as a listener to all events and commits the corresponding files at the end of the operations. The first version of the plugin can be really basic. On the long run since the current plugins are very limited it might be that the interface has to evolve a bit to accommodate this one. So if you are willing to contribute something it will be more than welcome and feel free to ask questions if something is unclear regarding how to integrate it in the current architecture.

**Comment by omangin** [comment]
That kind of depends on where this takes us. It is always a trade-off between introducing a new dependency and having to write the functionality by hand.

I am not so familiar with python git libraries but it seem that [GitPython](https://github.com/gitpython-developers/GitPython) and [pygit2](https://github.com/libgit2/pygit2) are two of the most common options.

In this case we currently do not have big needs so it is not clear that these libraries would bring much. In any case if we want one, we want one that is rather shallow since we only interact at the high level with git. I would suggest that you try to use subprocesses until you fill that your code for interacting with git is twice as big as what would be needed with any of the libraries, or until you fill reinventing the wheel. Then it will mean that it is probably time to switch to some library.

Importantly (and I am not sure how the libraries behave with respect to this), we want that user's git configs and preferences are used as much as possible as if they were directly interacting with git.

Please feel free to ask your specific questions on using subprocesses here so that everyone can help and that way we can keep track on the progress until there is a pull request!

**Comment by zamlz** [comment]
I too think its better just to use the subprocess to interact with git. Here is what I have so far.
https://github.com/zamlz/pubs/blob/git-plugin/pubs/plugs/git/git.py

So far adding, removing, renaming documents are committed to the git repo correctly as far as I'm aware. My next step is probably adding more listeners for other things like modifying notes, tags, etc.

The git shell though is the tricky part which needs to be looked at. The ideal behaviour I was thinking of is that the user could directly operate on the git repo with,

```
$ pubs git log --oneline
$ pubs git pull
$ pubs git push
```

So far, `pubs git push` and simple shells commands do work, but when adding more arguments to them like `pubs git log --oneline` it fails. How the shell commands are to be handled I guess is up for debate.

**Comment by omangin** [comment]
Thanks @zamlz! That looks like a great start! Actually it is pretty close to be merged. Could you open a pull request so that we can discuss the details there instead?

**Comment by zamlz** [comment]
Sorry I've been pretty late on this. I got really busy for past week. I'l get on that right now.
